name 'chef-metal-walker'
maintainer 'Andrew DuFour'
maintainer_email 'adufour@chef.io'
license 'all_rights'
description 'Installs/Configures chef-metal-winrm'
long_description 'Installs/Configures chef-metal-winrm'
version '0.1.0'
